-- =============================================
-- DROP TABLES
-- =============================================

DROP TABLE IF EXISTS project_skills;
DROP TABLE IF EXISTS project_sections;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS education;
DROP TABLE IF EXISTS experiences;
DROP TABLE IF EXISTS profile;


-- =============================================
-- PROFILE
-- =============================================

CREATE TABLE profile
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    location VARCHAR(255),

    status VARCHAR(50) NOT NULL DEFAULT 'OPEN_TO_WORK',

    email VARCHAR(255),

    profile_url VARCHAR(2048),
    github_url VARCHAR(2048),
    linkedin_url VARCHAR(2048),
    cv_url VARCHAR(2048)
);


-- =============================================
-- PROJECTS
-- =============================================

CREATE TABLE projects
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    slug VARCHAR(255) NOT NULL UNIQUE,

    title VARCHAR(255) NOT NULL,
    subtitle TEXT,

    client VARCHAR(255),
    role VARCHAR(255),

    start_date DATE,
    end_date DATE,

    description TEXT NOT NULL,

    status VARCHAR(50) NOT NULL DEFAULT 'ongoing',

    repository_url VARCHAR(2048),
    live_demo_url VARCHAR(2048),
    thumbnail_url VARCHAR(2048),

    is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    is_kodon_project BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT projects_date_check
        CHECK (
            end_date IS NULL
                OR start_date IS NULL
                OR end_date >= start_date
            )
);


-- =============================================
-- PROJECT SECTIONS
-- =============================================

CREATE TABLE project_sections
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    project_id INTEGER NOT NULL,

    display_order INTEGER NOT NULL,

    image_url VARCHAR(2048),

    image_position VARCHAR(50) NOT NULL DEFAULT 'none',

    content TEXT NOT NULL,

    CONSTRAINT fk_project_sections_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT unique_project_section_order
        UNIQUE (project_id, display_order)
);


-- =============================================
-- SKILLS
-- =============================================

CREATE TABLE skills
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name VARCHAR(255) NOT NULL UNIQUE,

    start_date DATE
);


-- =============================================
-- PROJECT SKILLS
-- =============================================

CREATE TABLE project_skills
(
    project_id INTEGER NOT NULL,

    skill_id INTEGER NOT NULL,

    PRIMARY KEY (project_id, skill_id),

    CONSTRAINT fk_project_skills_project
        FOREIGN KEY (project_id)
            REFERENCES projects(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_project_skills_skill
        FOREIGN KEY (skill_id)
            REFERENCES skills(id)
            ON DELETE RESTRICT
);


-- =============================================
-- EDUCATION
-- =============================================

CREATE TABLE education
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(255) NOT NULL,

    institution VARCHAR(255) NOT NULL,

    location VARCHAR(255),

    start_date DATE NOT NULL,

    end_date DATE,

    grade VARCHAR(255),

    description TEXT,

    CONSTRAINT education_date_check
        CHECK (
            end_date IS NULL
                OR end_date >= start_date
            )
);


-- =============================================
-- EXPERIENCES
-- =============================================

CREATE TABLE experiences
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    title VARCHAR(255) NOT NULL,

    company VARCHAR(255) NOT NULL,

    employment_type VARCHAR(50) NOT NULL,

    location VARCHAR(255),

    start_date DATE NOT NULL,

    end_date DATE,

    description TEXT,

    CONSTRAINT experiences_date_check
        CHECK (
            end_date IS NULL
                OR end_date >= start_date
            )
);
